#run using postman https://github.community/t5/GitHub-Actions/GitHub-Actions-Manual-Trigger-Approvals/m-p/33364#M1478
name: release

on: deployment

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: https://registry.npmjs.org/
    - name: get package version
        #https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-an-environment-variable-set-env
      run: echo "::set-env name=RELEASE_VERSION::$(jq -r '.version' package.json)"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        release_name: ${{ env.RELEASE_VERSION }}
        body: |
          Changes in this Release
          - uswds package updated to latest version
        draft: false
        prerelease: false
    - run: npm install
    - run: npm run release
    - run: echo "::set-env name=RELEASE_ASSET_PATH::$(find . -name "kswds-*.zip")"
    # https://askubuntu.com/a/682130
    - run: echo "::set-env name=RELEASE_ASSET_NAME::$(echo ${RELEASE_ASSET_PATH:2})"

    #https://github.com/actions/upload-release-asset
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ${{ env.RELEASE_ASSET_PATH }}
        asset_name: ${{ env.RELEASE_ASSET_NAME }}
        asset_content_type: application/zip
    #https://github.com/actions/starter-workflows/blob/master/ci/npm-publish.yml
    # remove .zip file
    - run: rm -rf ${{ env.RELEASE_ASSET_PATH }}
    - run: npm publish
      env:
        # https://stackoverflow.com/questions/57685065/how-to-set-secrets-in-github-actions
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
